repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: name-tests-test
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        types: [file, python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.930
    hooks:
     -  id: mypy
        files: pillow_heif/
        additional_dependencies: [pillow, cffi]

default_language_version:
    python: python3.9
