version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - libheif-dev

python:
  install:
    - method: pip
      path: .
      requirements: docs/rtd_docs_requirements.txt
