version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - cmake
    - nasm
    - libaom-dev
    - libx265-dev
    - libde265-dev

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
