#[build-system]
#requires = [
#    "setuptools>=41.2.0",
#    "cffi>=1.14.0",
#]
#build-backend = "setuptools.build_meta"
#
#[metadata]

[tool.black]
line-length = 120
target-versions = ["py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | \.vienv
  | \.env
  | \.mypy_cache
  | \.pytest_cache
  | __pycache__
  | build
  | dist
  | wheelhouse
)\
'''

[tool.mypy]
ignore_missing_imports = true
allow_redefinition = true
warn_no_return = true
strict_optional = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
addopts = "--ignore=memory_leaks.py"
