[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cffi",
]
# build-backend = "setuptools.build_meta"
#
#[metadata]

[tool.coverage.run]
cover_pylib = true
include = ["*/pillow_heif/*"]
omit = ["*/tests/*"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "DeprecationWarning"
]

[tool.black]
line-length = 120
target-versions = ["py37"]
preview = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.venv
  | \.vienv
  | \.env
  | \.mypy_cache
  | \.pytest_cache
  | __pycache__
  | build
  | dist
  | wheelhouse
)\
'''

[tool.isort]
profile = "black"

[tool.pylint]
master.py-version = "3.6"
master.unsafe-load-any-extension = "yes"
design.max-attributes = 10
classes.exclude-protected = [
    "_refs",
]
reports.output-format = "colorized"
similarities.ignore-imports = "yes"
messages_control.disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "line-too-long",
    "invalid-name",
]

[tool.mypy]
ignore_missing_imports = true
warn_no_return = true
strict_optional = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
