name: Analysis & Coverage

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, edited]
    paths:
      - 'pillow_heif/*.py'
      - 'libheif/*.py'
      - 'setup.*'
      - 'pyproject.toml'
      - 'tests/**'
  push:
    branches: [master]
    paths:
      - 'pillow_heif/*.py'
      - 'libheif/*.py'
      - 'setup.*'
      - 'pyproject.toml'
      - 'tests/**'
  workflow_dispatch:

jobs:
  build-analysis:
    runs-on: ubuntu-latest
    name: Analysis & Coverage
    steps:
      - uses: actions/checkout@v3
      - name: Prepare for source install
        run: |
          sudo -H python3 -m pip install --upgrade pip
          sudo -H python3 -m pip install -r requirements.txt
          sudo -H python3 -m pip install -r requirements_dev.txt
          sudo -H python3 -m pip install install pylint

      - name: Install from source
        run: sudo -H python3 -m pip -v install .

      - name: Pylint Analysis
        run: pylint --rcfile .pylintrc pillow_heif

      - name: Generate coverage report
        run: coverage run --rcfile=pyproject.toml -m pytest && coverage xml && coverage html

      - name: HTML coverage to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./htmlcov
          if-no-files-found: error

      - name: Upload report to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
