name: Analysis & Coverage

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, edited]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      py_src: ${{ steps.filter.outputs.py_src }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          py_src:
            - 'pillow_heif/*.py'
            - 'libheif/*.py'

  build-analysis:
    needs: [changes]
    if: ${{ needs.changes.outputs.py_src == 'true' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    name: Analysis & Coverage
    steps:
      - uses: actions/checkout@v2

      - name: pylint installation
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install -r requirements_dev.txt
          python3 -m pip install install pylint

      - name: Install from source
        run: sudo -H pip3 install .

      - name: Pylint Analysis
        run: pylint --rcfile .pylintrc pillow_heif

      - name: Generate coverage report
        run: coverage run --rcfile=pyproject.toml -m pytest && coverage xml

      - name: Upload report to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

  checks_status:
    needs: [changes, build-analysis]
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    name: checks-status
    runs-on: ubuntu-latest
    steps:
      - name: Checks passed
        run: echo "Checks passed"
