name: Build dependecies

on:
  workflow_dispatch:

jobs:
  dependencies_linux:
    strategy:
      fail-fast: true
      matrix:
        include:
          - runs-on: ubuntu-latest
            cibw-arch: manylinux_x86_64
#          - runs-on: ubuntu-latest
#            cibw-arch: manylinux_aarch64
    name: Dependecies • ${{ matrix.cibw-arch }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/cache@v2
        id: cache_pkg-config
        with:
          path: /build-tools
          key: ${{ matrix.runs-on }}-${{ matrix.cibw-arch }}-9-pkg-config-0.29.2

      - if: steps.cache_pkg-config.outputs.cache-hit != 'true'
        run: |
          BUILD_CMD="&& sh ./scripts/build__pkg-config.sh"
          echo BUILD_ALL="$BUILD_ALL $BUILD_CMD" >> $GITHUB_ENV

      - uses: actions/cache@v2
        id: cache_autoconf
        with:
          path: /build-tools
          key: ${{ matrix.runs-on }}-${{ matrix.cibw-arch }}-2-autoconf-2.71

      - if: steps.cache_autoconf.outputs.cache-hit != 'true'
        run: |
          BUILD_CMD="&& sh ./scripts/build__autoconf.sh"
          echo BUILD_ALL="$BUILD_ALL $BUILD_CMD" >> $GITHUB_ENV

      - name: DEBUG
        if: steps.cache_pkg-config.outputs.cache-hit != 'true'
        run: |
          echo "2"
          echo $BUILD_CMD
          echo $BUILD_ALL
          echo "3"
          echo "${{ env.BUILD_CMD }}"
          echo "${{ env.BUILD_ALL }}"
#
#      - name: Set up QEMU
#        if: matrix.cibw-arch == 'manylinux_aarch64'
#        uses: docker/setup-qemu-action@v1
#        with:
#          platforms: arm64

#      - name: Install requirements
#        run: |
#          echo $BUILD_LIST
#          echo $BUILD_CMD
#          echo "123"
#          echo "$BUILD_LIST"
#          echo "$BUILD_CMD"
#          echo "456"
#          echo ${{ env.BUILD_LIST }}
#          echo ${{ env.BUILD_CMD }}
#          python -m pip install cibuildwheel

#      - name: Run cibuildwheel
#        run: |
#          cibuildwheel
#        env:
#          CIBW_SKIP: *
