name: Build cache for dependecies

on:
  workflow_dispatch:

jobs:
  dependencies_linux:
    strategy:
      fail-fast: true
      matrix:
        cibw_buildlinux: [ manylinux, musllinux ]
        cibw_arch: [ "i686", "x86_64", "aarch64" ]
    name: ${{ matrix.cibw_arch }} • ${{ matrix.cibw_buildlinux }}
    runs-on: ubuntu-20.04
    env:
      KEY_HEAD: ${{ matrix.cibw_arch }}-${{ matrix.cibw_buildlinux }}
      BUILD_DIR_PREFIX: "/tmp/pillow_heif"

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        if: matrix.cibw_arch == 'aarch64'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Install cibuildwheel & twine
        run: python3 -m pip install cibuildwheel twine

      - name: manylinux preparations
        if: matrix.cibw_buildlinux == 'manylinux'
        run: echo INSTALL_OS_PACKAGES="yum update -y && yum install -y $OS_PACKAGES" >> $GITHUB_ENV
        env:
          OS_PACKAGES: "wget libtool git-all"

      - name: musllinux preparations
        if: matrix.cibw_buildlinux == 'musllinux'
        run: echo INSTALL_OS_PACKAGES="apk add --no-cache $OS_PACKAGES" >> $GITHUB_ENV
        env:
          OS_PACKAGES: "sudo py3-pip python3-dev libtool git \
          freetype-dev fribidi-dev harfbuzz-dev jpeg-dev lcms2-dev openjpeg-dev tiff-dev zlib-dev"

      - uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_DIR_PREFIX }}/build-tools
          key: ${{ env.KEY_HEAD }}-${{ hashFiles('libheif/*.py') }}

      - uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_DIR_PREFIX }}/build-stuff
          key: ${{ env.KEY_HEAD }}-${{ hashFiles('libheif/*.*') }}

      - name: Start test build
        run: cibuildwheel
        env:
          CIBW_BUILD: ${{ format('cp38-{0}*', matrix.cibw_buildlinux) }}
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          CIBW_BEFORE_ALL_LINUX: ${{ env.INSTALL_OS_PACKAGES }}
          CIBW_ENVIRONMENT_LINUX: BUILD_DIR_PREFIX=/host${{ env.BUILD_DIR_PREFIX }}
          CIBW_TEST_SKIP: "*"
          CIBW_BUILD_VERBOSITY: 1

      - name: Check builded wheel
        run: twine check wheelhouse/*

      - name: Upload builded wheel
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: wheelhouse/*.whl
          if-no-files-found: error
