name: Build dependecies

on:
  workflow_dispatch:

jobs:
  dependencies_linux:
    strategy:
      fail-fast: true
      matrix:
        include:
          - runs-on: ubuntu-latest
            cibw-arch: manylinux_x86_64
#          - runs-on: ubuntu-latest
#            cibw-arch: manylinux_aarch64
    name: Dependecies • ${{ matrix.cibw-arch }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: pkg-config
        shell: bash
        run: |
          echo "DEPENDENCY=pkg-config-0.29.2" >> $GITHUB_ENV
          echo "BUILD_CMD=scripts/build__pkg_config.sh" >> $GITHUB_ENV

      - name: Check
        uses: actions/cache@v2
        id: cache-${{ DEPENDENCY }}
        with:
          path: /build-tools
          key: ${{ matrix.cibw-arch }}-${{ DEPENDENCY }}

      - name: Add to build list
        if: steps.cache-${{ DEPENDENCY }}.outputs.cache-hit != 'true'
        run: echo "BUILD_LIST=${{ BUILD_LIST }}:${{ BUILD_CMD }}" >> $GITHUB_ENV

      - name: Set up QEMU
        if: matrix.cibw-arch == 'manylinux_aarch64'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Install requirements
        run: |
          python -m pip install cibuildwheel

#      - name: Run cibuildwheel
#        run: |
#          cibuildwheel
#        env:
#          CIBW_SKIP: *
