name: Build Light Version
# This action build Linux wheels without `aom` and `x265` libraries.

on:
  workflow_dispatch:

jobs:
  wheels_linux_cpython:
    strategy:
      fail-fast: true
      matrix:
        cibw_buildlinux: [ manylinux, musllinux ]
        cibw_arch: [ "aarch64", "i686", "x86_64" ]
    name: Wheels • ${{ matrix.cibw_buildlinux }} • ${{ matrix.cibw_arch }} • CPython
    runs-on: ubuntu-20.04
    env:
      BUILD_DIR_PREFIX: "/tmp/pillow_heif"
      KEY_HEAD: ${{ matrix.cibw_arch }}-${{ matrix.cibw_buildlinux }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        if: matrix.cibw_arch == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install cibuildwheel & twine
        run: python3 -m pip install cibuildwheel twine

      - name: manylinux preparations
        if: matrix.cibw_buildlinux == 'manylinux'
        run: echo INSTALL_OS_PACKAGES="yum makecache && yum install -y $OS_PACKAGES" >> $GITHUB_ENV
        env:
          OS_PACKAGES: "git-all libjpeg-turbo-devel lcms2-devel libffi-devel"

      - name: musllinux preparations
        if: matrix.cibw_buildlinux == 'musllinux'
        run: echo INSTALL_OS_PACKAGES="apk update && apk --no-cache add $OS_PACKAGES" >> $GITHUB_ENV
        env:
          OS_PACKAGES: "sudo py3-pip python3-dev fribidi-dev harfbuzz-dev jpeg-dev lcms2-dev openjpeg-dev"

      - name: Only minimal testing on aarch64
        if: matrix.cibw_arch == 'aarch64'
        run: echo CIBW_TEST_EXTRAS="tests-min" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ${{ env.BUILD_DIR_PREFIX }}/build-tools
          key: ${{ env.KEY_HEAD }}-${{ hashFiles('libheif/*.py') }}

      - name: Run cibuildwheel
        run: cibuildwheel
        env:
          CIBW_BUILD: ${{ format('cp3*-{0}_{1}', matrix.cibw_buildlinux, matrix.cibw_arch) }}
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          CIBW_BEFORE_ALL_LINUX: ${{ env.INSTALL_OS_PACKAGES }}
          CIBW_ENVIRONMENT_LINUX: BUILD_DIR_PREFIX=/host${{ env.BUILD_DIR_PREFIX }} PH_LIGHT=1

      - name: Checking built wheels
        run: twine check wheelhouse/*

      - name: Uploading wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/*.whl
          if-no-files-found: error

      - name: Fix cache permissions
        run: sudo chmod -R 777 ${{ env.BUILD_DIR_PREFIX }}

  wheels_linux_pypy:
    strategy:
      fail-fast: true
      matrix:
        cibw_buildlinux: [ manylinux ]
        cibw_arch: [ "aarch64", "i686", "x86_64" ]
        cibw_build: [ "pp37", "pp38" ]
    name: Wheels • ${{ matrix.cibw_buildlinux }} • ${{ matrix.cibw_arch }} • ${{ matrix.cibw_build }}
    runs-on: ubuntu-20.04
    env:
      BUILD_DIR_PREFIX: "/tmp/pillow_heif"
      KEY_HEAD: ${{ matrix.cibw_arch }}-${{ matrix.cibw_buildlinux }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        if: matrix.cibw_arch == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Install cibuildwheel & twine
        run: python3 -m pip install cibuildwheel twine

      - name: Only minimal testing on aarch64
        if: matrix.cibw_arch == 'aarch64'
        run: echo CIBW_TEST_EXTRAS="tests-min" >> $GITHUB_ENV

      - uses: actions/cache@v3
        with:
          path: ${{ env.BUILD_DIR_PREFIX }}/build-tools
          key: ${{ env.KEY_HEAD }}-${{ hashFiles('libheif/*.py') }}

      - name: Run cibuildwheel
        run: cibuildwheel
        env:
          CIBW_BUILD: ${{ format('{0}-{1}_{2}', matrix.cibw_build , matrix.cibw_buildlinux, matrix.cibw_arch) }}
          CIBW_ARCHS: ${{ matrix.cibw_arch }}
          CIBW_BEFORE_ALL_LINUX: "yum makecache && yum install -y git-all libjpeg-turbo-devel lcms2-devel libffi-devel"
          CIBW_ENVIRONMENT_LINUX: BUILD_DIR_PREFIX=/host${{ env.BUILD_DIR_PREFIX }} PH_LIGHT=1

      - name: Checking built wheels
        run: twine check wheelhouse/*

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: wheelhouse/*.whl
          if-no-files-found: error

      - name: Fix cache permissions
        run: sudo chmod -R 777 ${{ env.BUILD_DIR_PREFIX }}
