name: Build dependecies

on:
  workflow_dispatch:

jobs:
  dependencies_linux:
    strategy:
      fail-fast: true
      matrix:
        include:
          - runs-on: ubuntu-latest
            cibw-arch: manylinux_x86_64
#          - runs-on: ubuntu-latest
#            cibw-arch: manylinux_aarch64
    name: Dependecies • ${{ matrix.cibw-arch }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Make preparations
        run: |
          sudo mkdir /build-tools
          sudo chmod 777 /build-tools
          echo SCRIPTS_DIR="./build_scripts/linux" >> $GITHUB_ENV

      - run: |
          BUILD_CMD="&& sh $SCRIPTS_DIR/$NAME.sh $VERSION"
          echo BUILD_CMD="$BUILD_CMD" >> $GITHUB_ENV
          echo STUFF_PATH="/build-tools/$NAME-$VERSION" >> $GITHUB_ENV
          echo CACHE_KEY=${{ env.NAME }}-${{ env.VERSION }}-0 >> $GITHUB_ENV
          echo BUILD_CMD_LIST="$BUILD_CMD_LIST $BUILD_CMD" >> $GITHUB_ENV
        env:
          NAME: "pkg-config"
          VERSION: "0.29.2"

      - name: Debug1
        run: |
          echo $BUILD_CMD
          echo $STUFF_PATH
          echo $SCRIPTS_DIR
          echo $CACHE_KEY
          echo $CACHE_KEY
          echo $BUILD_CMD_LIST

      - uses: actions/cache@v2
        id: cache-pkg_config
        with:
          path: ${{ env.STUFF_PATH }}
          key: ${{ matrix.runs-on }}-${{ matrix.cibw-arch }}-${{ env.CACHE_KEY }}
#
#      - if: steps.${{ env.CACHE_STEP_ID }}.outputs.cache-hit != 'true'
#        run: |
#          echo BUILD_CMD="&& sh $SCRIPTS_DIR/$NAME.sh $VERSION" >> $GITHUB_ENV

#      - uses: actions/cache@v2
#        id: cache_autoconf
#        with:
#          path: /build-tools
#          key: ${{ matrix.runs-on }}-${{ matrix.cibw-arch }}-07-autoconf-2.71
#
#      - if: steps.cache_autoconf.outputs.cache-hit != 'true'
#        run: |
#          BUILD_CMD="&& sh ./build_scripts/linux/autoconf.sh"
#          echo BUILD_CMD_LIST="$BUILD_CMD_LIST $BUILD_CMD" >> $GITHUB_ENV
#
#      - uses: actions/cache@v2
#        id: cache_automake
#        with:
#          path: /build-tools
#          key: ${{ matrix.runs-on }}-${{ matrix.cibw-arch }}-08-automake-1.16.4
#
#      - if: steps.cache_automake.outputs.cache-hit != 'true'
#        run: |
#          BUILD_CMD="&& sh ./build_scripts/linux/automake.sh"
#          echo BUILD_CMD_LIST="$BUILD_CMD_LIST $BUILD_CMD" >> $GITHUB_ENV

      - name: Preparations for build start
        run: |
          echo BUILD_COMMAND="set -ex $BUILD_CMD_LIST" >> $GITHUB_ENV
          echo "CIBW_BUILD=*-${{ matrix.cibw-arch }}" >> $GITHUB_ENV
#
#      - name: Set up QEMU
#        if: env.BUILD_COMMAND != '' && matrix.cibw-arch == 'manylinux_aarch64'
#        uses: docker/setup-qemu-action@v1
#        with:
#          platforms: arm64
#
#      - name: Install requirements
#        run: |
#          python -m pip install cibuildwheel
#
#      - name: x64 linux pre configure enviroment
#        if: matrix.cibw-arch == 'manylinux_x86_64'
#        run: |
#          echo "CIBW_ARCHS=x86_64" >> $GITHUB_ENV
#          echo "CIBW_MANYLINUX_X86_64_IMAGE=manylinux2014" >> $GITHUB_ENV
#          echo "CIBW_BUILD=cp38-manylinux_x86_64" >> $GITHUB_ENV
#
#      - name: Arm linux pre configure enviroment
#        if: matrix.cibw-arch == 'manylinux_aarch64'
#        run: |
#          echo "CIBW_ARCHS=aarch64" >> $GITHUB_ENV
#          echo "CIBW_BUILD=cp38-manylinux_aarch64" >> $GITHUB_ENV
#
#      - name: Start test build
#        run: |
#          cibuildwheel --config-file "{package}/build_scripts/dependencies.toml"
#        env:
#          CIBW_BEFORE_ALL: ${{ env.BUILD_COMMAND }}
#          CIBW_TEST_SKIP: "*"
#          CIBW_REPAIR_WHEEL_COMMAND: ""
