name: Docs

on:
  release:
    types: [created]
  push:
    branches:
    - main
  workflow_dispatch:


concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: True

jobs:
    doc:
      name: "Documentation build"
      runs-on: ubuntu-20.04
      env:
        BUILD_DIR_PREFIX: "/tmp/pillow_heif"
        KEY_HEAD: x86_64-manylinux

      steps:
        - uses: actions/checkout@v3

        - uses: actions/cache@v3
          with:
            path: ${{ env.BUILD_DIR_PREFIX }}/build-tools
            key: ${{ env.KEY_HEAD }}-${{ hashFiles('libheif/*.py') }}

        - uses: actions/cache@v3
          with:
            path: ${{ env.BUILD_DIR_PREFIX }}/build-stuff
            key: ${{ env.KEY_HEAD }}-${{ hashFiles('libheif/*.*') }}

        - name: Build sdist
          run: sudo -H python3 -m pip install .[docs]

        - name: Build documentations
          shell: bash -l {0}
          run: |
            sphinx-multiversion docs/ build/html
            touch build/html/.nojekyll
            ln -srf build/html/$(git tag -l --sort=creatordate |tail -1) build/html/latest  # auto-link the latest tag

        - name: Push to web
          uses: tagus/git-deploy@v0.4.1
          with:
            changes: build/html
            branch: main
            repository: git@github.com:bigcat88/pillow_heif.git
            ssh_key: ${{ secrets.DOCS_DEPLOY_KEY }}
            name: pillow-heif
            email: bigcat88@icloud.com
            clean_repo: true

        - name: Fix cache permissions
          run: sudo chmod -R 777 ${{ env.BUILD_DIR_PREFIX }}
