name: 'Pre-commit autoupdate'

on:
  schedule:
    - cron: '0 10 * * 0' # Every day at 12:00 PM (GMT+2)
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python3 -m pip install pre-commit

      - run: pre-commit autoupdate
        shell: bash

      - run: pre-commit run --all-files
        shell: bash

      - uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
