name: Publish

on:
  push:
    branches: [ master ]

jobs:
  trigger_pillow_heif_build:
    if: "contains(github.event.head_commit.message, '[publish]')"
    name: Pillow-Heif
    uses: ./.github/workflows/publish-pypi.yml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_PILLOW_HEIF }}

  trigger_pi_heif_build:
    needs: [trigger_pillow_heif_build]
    if: "contains(github.event.head_commit.message, '[publish]')"
    name: Pi-Heif
    uses: ./.github/workflows/publish-pypi-pi_heif.yml
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN_PI_HEIF }}
