name: Publish

on:
  push:
    branches: [ master ]

jobs:
  trigger_build:
    if: "contains(github.event.head_commit.message, '[publish]')"
    name: Publish triggered
    uses: .github/workflows/publish-pypi.yml@main
