name: Publish

on:
  push:
    branches: [ master ]

jobs:
  publish_wheels:
    name: Publish triggered
    if: "contains(github.event.head_commit.message, '[publish]')"
    runs-on: ubuntu-20.04

    steps:
      - run: echo "Publish triggered"
