name: test

on:
  workflow_dispatch:

jobs:
  wheel_armv7l:
    name: Wheels • Alpine 3.14+ • ARMv7l • CPython3.8+
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build pillow_heif
        run: |
          mkdir dock_out
          docker buildx build --output type=local,dest=./dock_out --platform "linux/arm/v7" -f docker/test.Dockerfile .
          ls -la ./dock_out/pillow_heif/repaired_dist

      - name: Checking built wheels
        run: |
          python3 -m pip install twine
          twine check ./dock_out/pillow_heif/repaired_dist/*

      - name: Uploading wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./dock_out/pillow_heif/repaired_dist/*.whl
          if-no-files-found: error
