name: Build from source

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
    types: [opened, reopened, edited]
    paths:
      - 'libheif/*.*'
      - 'setup.*'
      - 'pyproject.toml'
      - 'tests/**'
  push:
    branches: [master]
    paths:
      - 'libheif/*.*'
      - 'setup.*'
      - 'pyproject.toml'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.distro }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[docs]')"
    strategy:
      fail-fast: false
      matrix:
#        distro: ["ubuntu:focal", "ubuntu:jammy", "alpine:3.15"]
#        arch: ["linux/amd64", "linux/arm64", "linux/arm/v7"]
        distro: ["alpine:3.14"]
        arch: ["linux/amd64"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up qemu
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build pillow_heif
        run: |
          docker buildx build --platform ${{ matrix.arch }} --build-arg DISTRO="${{ matrix.distro }}" -f docker/from_src.Dockerfile .
