name: Build from source(Alpine_3_15)

on:
  workflow_dispatch:

jobs:
  test_src_build:
    name: ${{ matrix.docker_file }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[docs]')"
    strategy:
      matrix:
        arch: ["amd64", "arm64", "arm/v7"]
        docker_file: ["Alpine_3_15"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Requirements
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/from_src/${{ matrix.docker_file }}.Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: false
          cache-from: type=gha,scope=t1-${{ matrix.docker_file }}-${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=t1-${{ matrix.docker_file }}-${{ matrix.arch }}
          target: base

      - name: Build & Test Pillow-Heif
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/from_src/${{ matrix.docker_file }}.Dockerfile
          platforms: linux/${{ matrix.arch }}
          push: false
          cache-from: type=gha,scope=t1-${{ matrix.docker_file }}-${{ matrix.arch }}
          target: build_test
