name: Build from source(macOS)

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths:
      - 'libheif/macos/**'
      - 'libheif/build.py'
      - 'libheif/public_api.h'
      - 'setup.*'
      - 'pyproject.toml'
  push:
    paths:
      - 'libheif/macos/**'
      - 'libheif/build.py'
      - 'libheif/public_api.h'
      - 'setup.*'
      - 'pyproject.toml'

concurrency:
  group: src_macos-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos_11:
    name: macOS:11-x86_64
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v4
#        with:
#          python-version: '3.8'
#
#      - name: Install libheif from formula
#        run: |
#          brew uninstall --force --ignore-dependencies imagemagick
#          brew install --formula ./libheif/macos/libheif.rb
#
#      - name: Installing Pillow-Heif
#        run: python3 -m pip -v install ".[dev]"
#
#      - name: LibHeif info
#        run: python3 -c "import pillow_heif; print(pillow_heif.libheif_info())"
#
#      - name: Perform tests
#        run: python3 -m pytest -rs
