name: Nightly source build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

jobs:
  src-build-linux:
    uses: ./.github/workflows/test-src-build-linux.yml
  src-build-macos:
    uses: ./.github/workflows/test-src-build-macos.yml
  src-build-windows:
    uses: ./.github/workflows/test-src-build-windows.yml
